express:
  port: 9000

api:
  url: http://localhost:9000

web:
  url: http://localhost:8080

faye:
  url: http://localhost:8000/faye
  secret: meh

auth:
  secret: secret
  github:
    id: put-github-id-here
    secret: put-github-secret-here
