express:
  port: 9000

api:
  url: http://localhost:9000

web:
  url: http://localhost:8080

faye:
  url: http://localhost:8000/faye
  secret: meh

auth:
  secret: secret
  github:
    id: fddc62938df93ec4126d
    secret: b15c1628cea72e5056decf83285cfd983d94c004
